name: Request a feature in Kodi Search card
description: Request a feature in Kodi Search card
labels: enhancement
assignees: 'jtbgroup'
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests or enhancements only!

        If you have a bug or a question, please use the dedicated form.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    validations:
      required: true
    attributes:
      label: Proposition
      description: >-
        A clear and concise description of what you want to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Alternatives
      description: >-
        A clear and concise description of any alternative propositions or features you've considered.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Context
      description: >-
        Add any other context about the feature request here.
