resources:
  - url: http://127.0.0.1:5000/kodi-search-card.js
    type: module
views:
  - cards:
      - type: custom:kodi-search-card
        name: Kodi Search Card Development
        entity: sun.sun
        test_gui: true
