name: Release

on:
  release:
    types: [published]

jobs:
  validate_hacs:
    name: Validate HACS requirements
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"

  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Build
      - name: Build the file
        run: |
          cd /home/runner/work/kodi-musicbrainz-card/kodi-musicbrainz-card
          npm install
          npm run build

      # Upload build file to the releas as an asset.
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/kodi-musicbrainz-card/kodi-musicbrainz-card/dist/kodi-musicbrainz-card.js
          asset_name: kodi-musicbrainz-card.js
          tag: ${{ github.ref }}
          overwrite: true